### ISSUE TITLE
FM POPUP_TO_DISPLAY_TEXT_LO not available in 7.51 02 dev edition

### ISSUE THREAD

**Issue by christianguenter2** [tricktresor/gladius#1]
FM POPUP_TO_DISPLAY_TEXT_LO is not part of bare netweaver systems.
![image](https://user-images.githubusercontent.com/17437789/43048793-94b987b0-8ded-11e8-9f8c-bf3da4af009d.png)

**Comment by tricktresor** [comment]
Changed to Popup_To_inform
