### ISSUE TITLE
Failed to activate ZGLDS_DEMO_USR

### ISSUE THREAD

**Issue by hendrik77** [tricktresor/gladius#2]
hi,

the DB table cannot be activated - error msg:

> ZGLDS_DEMO_USR-SOURCECODE: Too long for activation of 'not null' flag (>255)				

![image](https://user-images.githubusercontent.com/5760151/89873216-6306a000-dbba-11ea-932a-4e98f056ac30.png)

![image](https://user-images.githubusercontent.com/5760151/89873243-6b5edb00-dbba-11ea-8376-bdff26011679.png)

Cheers
Hendrik

**Comment by flo-pi** [comment]
If you go to table definition in SE11 and deactivate the "Initial Values" Flag of field "SOURCECODE" the table could be activated.
Maybe it debends on Netweaver release...

**Comment by hendrik77** [comment]
Thanks! Works now. 

ABAP PLATFORM	1909.
